version: '3'

services:
  node:
    container_name: node-container-3
    build:
      context: .
    environment:
    - CONTAINER_PORT=${CONTAINER_PORT}
    working_dir: /home/node/lab
    ports:
    - '${HOST_PORT}:${CONTAINER_PORT}'
    volumes:
    - ./resources/db.json:/home/node/lab/db.json