version: '3'

services:
  nginx:
    container_name: nginx-container-4
    image: nginx:latest
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
    - "8080:8080"

  lite-server-node:
    image: node:16
    working_dir: /home/node/lab
    volumes:
    - ./lite-server/index.html:/home/node/lab/index.html
    expose: 
    - "${LITE_SERVER_EXPOSE_PORT}"
    command: > 
      bash -c 'npm init -y 
      && npm i -g lite-server 
      && lite-server'

  json-server-node:
    image: node:16
    working_dir: /home/node/lab
    volumes:
    - ./json-server/db.json:/home/node/lab/db.json
    expose: 
    - "${JSON_SERVER_EXPOSE_PORT}"
    command: > 
      bash -c 'npm init -y
      && npm i -g json-server 
      && json-server --port ${JSON_SERVER_CONTAINER_PORT} --host 0.0.0.0 --watch /home/node/lab/db.json'