version: '3'

services:
  nginx:
    container_name: nginx-container-4
    image: nginx:latest
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
    - "8080:8080"

  lite-server-node:
    build: ./lite-server
    working_dir: /home/node/lab
    volumes:
    - ./lite-server/index.html:/home/node/lab/index.html
    expose:
    - "${LITE_SERVER_EXPOSE_PORT}"

  json-server-node:
    build: 
      context: ./json-server
    environment:
    - JSON_SERVER_PORT=${JSON_SERVER_PORT}
    working_dir: /home/node/lab
    volumes:
    - ./json-server/db.json:/home/node/lab/db.json
    expose:
    - "${JSON_SERVER_PORT}"